export default {
    ASSIGNED_WALKER: "/walkers/assignedwalks/:credential_id",
    HISTORY: "/history",
    DOGS: "/dogs",
    OWNER_PROFILE: "/ownerprofile",
    LISTINGS_DETAIL: "/listings/detail/",
    LISTING_DETAIL_BY_ID: "/listings/detail/:bookingId",
    ABOUT: "/about",
    PROFILE_WALKER: "/profile/walker",
    PROFILE_OWNER: "/profile/owner",
    EDIT_PROFILE_WALKER: "/profile/walker/edit",
    EDIT_PROFILE_OWNER: "/profile/owner/edit",
    WALKERS: "/walkers",
    OWNERS: "/owners",
    OWNER: "/owners/:credentialId",
    DASHBOARD_WALKER: "/dashboard/walker",
    DASHBOARD_OWNER: "/dashboard/owner",
    LOGIN: "/login",
    SIGN_UP: "/signup",
    NEW_LISTINGS: "/newlistings",
    HOME: "/",
    NOT_FOUND: "/notfound",
    CREATE_LISTING_OWNER: "/listings/create",
    CALENDAR: "/calendar",
    SOCIAL: "/social",
};
