export default {
    DOGS: "/dogs",
    OWNER_PROFILE: "/ownerprofile",
    LISTINGS_DETAIL: "/listings/detail/",
    LISTING_DETAIL_BY_ID: "/listings/detail/:bookingId",
    ABOUT: "/about",
    PROFILE: "/profile",
    WALKERS: "/walkers",
    OWNERS: "/owners",
    DASHBOARD: "/dashboard",
    LOGIN: "/login",
    SIGN_UP: "/signup",
    NEW_LISTINGS: "/newlistings",
    HOME: "/",
    NOT_FOUND: "/notfound",
};
